# Generated by Django 5.1.4 on 2024-12-11 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='post_images/')),
                ('sender_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sender_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('sender_address', models.TextField(blank=True, null=True)),
                ('sender_pincode', models.CharField(blank=True, max_length=6, null=True)),
                ('receiver_name', models.CharField(blank=True, max_length=255, null=True)),
                ('receiver_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('receiver_address', models.TextField(blank=True, null=True)),
                ('receiver_pincode', models.CharField(blank=True, max_length=6, null=True)),
                ('modified_receiver_pincode', models.CharField(blank=True, max_length=6, null=True)),
                ('receiver_latitude', models.TextField(blank=True, null=True)),
                ('receiver_longitude', models.TextField(blank=True, null=True)),
                ('customer_feedback', models.TextField(blank=True, null=True)),
                ('chat_status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
