# Generated by Django 5.1.4 on 2024-12-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PincodeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_pincode', models.CharField(help_text='The old pincode that has been merged.', max_length=6, unique=True)),
                ('new_pincode', models.CharField(help_text='The new merged pincode.', max_length=6)),
            ],
        ),
    ]
