# Generated by Django 5.1.4 on 2024-12-11 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_pincodemapping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postdata',
            old_name='image',
            new_name='image1',
        ),
    ]
